# `dependabot.yml` file with
#  assignee for all JavaScript dependency pull requests

version: 2
updates:
  # Keep pnpm-managed dependencies up to date
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    # Raise dependency pull requests with assignees
    assignees:
      - "dedkola"
